# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength, Metrics/MethodLength

module Relationships
  class RelationshipType
    def relationship_type(type_code)
      short_type = relationship_code.find { |type| type[:system_id] == type_code }
      short_type ? short_type[:short_description] : ''
    end

    private

    def relationship_code
      [
        {
          'system_id': 175,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'A',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Aunt/Nephew (Maternal)',
          'long_description': '255'
        },
        {
          'system_id': 176,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'A',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Aunt/Nephew (Paternal)',
          'long_description': '256'
        },
        {
          'system_id': 177,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'A',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Aunt/Niece (Maternal)',
          'long_description': '263'
        },
        {
          'system_id': 178,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'A',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Aunt/Niece (Paternal)',
          'long_description': '264'
        },
        {
          'system_id': 179,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'BR',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Brother/Brother',
          'long_description': '179'
        },
        {
          'system_id': 180,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'BR',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Brother/Brother (Half)',
          'long_description': '180'
        },
        {
          'system_id': 181,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'BR',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Brother/Brother (Step)',
          'long_description': '181'
        },
        {
          'system_id': 182,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'BR',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Brother/Sister',
          'long_description': '276'
        },
        {
          'system_id': 183,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'BR',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Brother/Sister (Half)',
          'long_description': '277'
        },
        {
          'system_id': 184,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'BR',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Brother/Sister (Step)',
          'long_description': '278'
        },
        {
          'system_id': 185,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'CS',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Cousin/Cousin (Maternal)',
          'long_description': '185'
        },
        {
          'system_id': 186,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'CS',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Cousin/Cousin (Paternal)',
          'long_description': '186'
        },
        {
          'system_id': 187,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'FU',
          'inactive_indicator': false,
          'short_description': 'Daughter/De Facto Parent',
          'long_description': '201'
        },
        {
          'system_id': 188,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fM',
          'inactive_indicator': false,
          'short_description': 'Daughter/Father (Adoptive)',
          'long_description': '203'
        },
        {
          'system_id': 189,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fM',
          'inactive_indicator': false,
          'short_description': 'Daughter/Father (Alleged)',
          'long_description': '204'
        },
        {
          'system_id': 190,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fM',
          'inactive_indicator': false,
          'short_description': 'Daughter/Father (Birth)',
          'long_description': '205'
        },
        {
          'system_id': 191,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FD',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Daughter/Father (Foster)',
          'long_description': '206'
        },
        {
          'system_id': 192,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fM',
          'inactive_indicator': false,
          'short_description': 'Daughter/Father (Presumed)',
          'long_description': '207'
        },
        {
          'system_id': 193,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SD',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Daughter/Father (Step)',
          'long_description': '208'
        },
        {
          'system_id': 194,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fF',
          'inactive_indicator': false,
          'short_description': 'Daughter/Mother (Adoptive)',
          'long_description': '245'
        },
        {
          'system_id': 195,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fF',
          'inactive_indicator': false,
          'short_description': 'Daughter/Mother (Alleged)',
          'long_description': '246'
        },
        {
          'system_id': 196,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fF',
          'inactive_indicator': false,
          'short_description': 'Daughter/Mother (Birth)',
          'long_description': '247'
        },
        {
          'system_id': 197,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FD',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Daughter/Mother (Foster)',
          'long_description': '248'
        },
        {
          'system_id': 198,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'fF',
          'inactive_indicator': false,
          'short_description': 'Daughter/Mother (Presumed)',
          'long_description': '5620'
        },
        {
          'system_id': 199,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SD',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Daughter/Mother (Step)',
          'long_description': '249'
        },
        {
          'system_id': 200,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'D',
          'third_id': '0000000000',
          'other_code': 'FU',
          'inactive_indicator': true,
          'short_description': 'Daughter/Non-Custodial Parent',
          'long_description': '272'
        },
        {
          'system_id': 201,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'DFP',
          'third_id': '0000000000',
          'other_code': 'UF',
          'inactive_indicator': false,
          'short_description': 'De Facto Parent/Daughter',
          'long_description': '187'
        },
        {
          'system_id': 202,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'DFP',
          'third_id': '0000000000',
          'other_code': 'UM',
          'inactive_indicator': false,
          'short_description': 'De Facto Parent/Son',
          'long_description': '282'
        },
        {
          'system_id': 203,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mf',
          'inactive_indicator': false,
          'short_description': 'Father/Daughter (Adoptive)',
          'long_description': '188'
        },
        {
          'system_id': 204,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mf',
          'inactive_indicator': false,
          'short_description': 'Father/Daughter (Alleged)',
          'long_description': '189'
        },
        {
          'system_id': 205,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mf',
          'inactive_indicator': false,
          'short_description': 'Father/Daughter (Birth)',
          'long_description': '190'
        },
        {
          'system_id': 206,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FF',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Father/Daughter (Foster)',
          'long_description': '191'
        },
        {
          'system_id': 207,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mf',
          'inactive_indicator': false,
          'short_description': 'Father/Daughter (Presumed)',
          'long_description': '192'
        },
        {
          'system_id': 208,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SF',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Father/Daughter (Step)',
          'long_description': '193'
        },
        {
          'system_id': 209,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mm',
          'inactive_indicator': false,
          'short_description': 'Father/Son (Adoptive)',
          'long_description': '283'
        },
        {
          'system_id': 210,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mm',
          'inactive_indicator': false,
          'short_description': 'Father/Son (Alleged)',
          'long_description': '284'
        },
        {
          'system_id': 211,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mm',
          'inactive_indicator': false,
          'short_description': 'Father/Son (Birth)',
          'long_description': '285'
        },
        {
          'system_id': 212,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FF',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Father/Son (Foster)',
          'long_description': '286'
        },
        {
          'system_id': 213,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'F',
          'third_id': '0000000000',
          'other_code': 'Mm',
          'inactive_indicator': false,
          'short_description': 'Father/Son (Presumed)',
          'long_description': '287'
        },
        {
          'system_id': 214,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SF',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Father/Son (Step)',
          'long_description': '288'
        },
        {
          'system_id': 215,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Godchild/Godparent',
          'long_description': '216'
        },
        {
          'system_id': 216,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SR',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Godparent/Godchild',
          'long_description': '215'
        },
        {
          'system_id': 217,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GD',
          'third_id': '0000000000',
          'other_code': 'FU',
          'inactive_indicator': false,
          'short_description': 'Granddaughter/Grandparent (Maternal)',
          'long_description': '221'
        },
        {
          'system_id': 218,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GD',
          'third_id': '0000000000',
          'other_code': 'FU',
          'inactive_indicator': false,
          'short_description': 'Granddaughter/Grandparent (Paternal)',
          'long_description': '222'
        },
        {
          'system_id': 219,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GD',
          'third_id': '0000000000',
          'other_code': 'FU',
          'inactive_indicator': false,
          'short_description': 'Granddaughter/Great Grandparent (Matrnl)',
          'long_description': '231'
        },
        {
          'system_id': 220,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GD',
          'third_id': '0000000000',
          'other_code': 'FU',
          'inactive_indicator': false,
          'short_description': 'Granddaughter/Great Grandparent (Patrnl)',
          'long_description': '232'
        },
        {
          'system_id': 221,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GP',
          'third_id': '0000000000',
          'other_code': 'UF',
          'inactive_indicator': false,
          'short_description': 'Grandparent/Granddaughter (Maternal)',
          'long_description': '217'
        },
        {
          'system_id': 222,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GP',
          'third_id': '0000000000',
          'other_code': 'UF',
          'inactive_indicator': false,
          'short_description': 'Grandparent/Granddaughter (Paternal)',
          'long_description': '218'
        },
        {
          'system_id': 223,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GP',
          'third_id': '0000000000',
          'other_code': 'UM',
          'inactive_indicator': false,
          'short_description': 'Grandparent/Grandson (Maternal)',
          'long_description': '225'
        },
        {
          'system_id': 224,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GP',
          'third_id': '0000000000',
          'other_code': 'UM',
          'inactive_indicator': false,
          'short_description': 'Grandparent/Grandson (Paternal)',
          'long_description': '226'
        },
        {
          'system_id': 225,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GS',
          'third_id': '0000000000',
          'other_code': 'MU',
          'inactive_indicator': false,
          'short_description': 'Grandson/Grandparent (Maternal)',
          'long_description': '223'
        },
        {
          'system_id': 226,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GS',
          'third_id': '0000000000',
          'other_code': 'MU',
          'inactive_indicator': false,
          'short_description': 'Grandson/Grandparent (Paternal)',
          'long_description': '224'
        },
        {
          'system_id': 227,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GS',
          'third_id': '0000000000',
          'other_code': 'MU',
          'inactive_indicator': false,
          'short_description': 'Grandson/Great Grandparent (Maternal)',
          'long_description': '233'
        },
        {
          'system_id': 228,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GS',
          'third_id': '0000000000',
          'other_code': 'MU',
          'inactive_indicator': false,
          'short_description': 'Grandson/Great Grandparent (Paternal)',
          'long_description': '234'
        },
        {
          'system_id': 229,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Great Aunt/Niece (Maternal)',
          'long_description': '265'
        },
        {
          'system_id': 230,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Great Aunt/Niece (Paternal)',
          'long_description': '266'
        },
        {
          'system_id': 231,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UF',
          'inactive_indicator': false,
          'short_description': 'Great Grandparent/Granddaughter (Matrnl)',
          'long_description': '219'
        },
        {
          'system_id': 232,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UF',
          'inactive_indicator': false,
          'short_description': 'Great Grandparent/Granddaughter (Patrnl)',
          'long_description': '220'
        },
        {
          'system_id': 233,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UM',
          'inactive_indicator': false,
          'short_description': 'Great Grandparent/Grandson (Maternal)',
          'long_description': '227'
        },
        {
          'system_id': 234,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UM',
          'inactive_indicator': false,
          'short_description': 'Great Grandparent/Grandson (Paternal)',
          'long_description': '228'
        },
        {
          'system_id': 235,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Great Uncle/Niece (Maternal)',
          'long_description': '267'
        },
        {
          'system_id': 236,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Great Uncle/Niece (Paternal)',
          'long_description': '268'
        },
        {
          'system_id': 237,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Great-Aunt/Nephew (Maternal)',
          'long_description': '257'
        },
        {
          'system_id': 238,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Great-Aunt/Nephew (Paternal)',
          'long_description': '258'
        },
        {
          'system_id': 239,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Great-Uncle/Nephew (Maternal)',
          'long_description': '259'
        },
        {
          'system_id': 240,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Great-Uncle/Nephew (Paternal)',
          'long_description': '260'
        },
        {
          'system_id': 241,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'GU',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Guardian/Ward',
          'long_description': '301'
        },
        {
          'system_id': 242,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Indian Child/Indian Custodian',
          'long_description': '243'
        },
        {
          'system_id': 243,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SR',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Indian Custodian/Indian Child',
          'long_description': '242'
        },
        {
          'system_id': 244,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'BD',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Live-in/Live-in',
          'long_description': '244'
        },
        {
          'system_id': 245,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Ff',
          'inactive_indicator': false,
          'short_description': 'Mother/Daughter (Adoptive)',
          'long_description': '194'
        },
        {
          'system_id': 246,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Ff',
          'inactive_indicator': false,
          'short_description': 'Mother/Daughter (Alleged)',
          'long_description': '195'
        },
        {
          'system_id': 247,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Ff',
          'inactive_indicator': false,
          'short_description': 'Mother/Daughter (Birth)',
          'long_description': '196'
        },
        {
          'system_id': 248,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FM',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Mother/Daughter (Foster)',
          'long_description': '197'
        },
        {
          'system_id': 249,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SM',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Mother/Daughter (Step)',
          'long_description': '199'
        },
        {
          'system_id': 250,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Fm',
          'inactive_indicator': false,
          'short_description': 'Mother/Son (Adoptive)',
          'long_description': '289'
        },
        {
          'system_id': 251,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Fm',
          'inactive_indicator': false,
          'short_description': 'Mother/Son (Alleged)',
          'long_description': '290'
        },
        {
          'system_id': 252,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Fm',
          'inactive_indicator': false,
          'short_description': 'Mother/Son (Birth)',
          'long_description': '291'
        },
        {
          'system_id': 253,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FM',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Mother/Son (Foster)',
          'long_description': '292'
        },
        {
          'system_id': 254,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SM',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Mother/Son (Step)',
          'long_description': '293'
        },
        {
          'system_id': 255,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Nephew/Aunt (Maternal)',
          'long_description': '175'
        },
        {
          'system_id': 256,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Nephew/Aunt (Paternal)',
          'long_description': '176'
        },
        {
          'system_id': 257,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Nephew/Great-Aunt (Maternal)',
          'long_description': '237'
        },
        {
          'system_id': 258,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Nephew/Great-Aunt (Paternal)',
          'long_description': '238'
        },
        {
          'system_id': 259,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Nephew/Great-Uncle (Maternal)',
          'long_description': '239'
        },
        {
          'system_id': 260,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Nephew/Great-Uncle (Paternal)',
          'long_description': '240'
        },
        {
          'system_id': 261,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Nephew/Uncle (Maternal)',
          'long_description': '296'
        },
        {
          'system_id': 262,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NP',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Nephew/Uncle (Paternal)',
          'long_description': '297'
        },
        {
          'system_id': 263,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Niece/Aunt (Maternal)',
          'long_description': '177'
        },
        {
          'system_id': 264,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Niece/Aunt (Paternal)',
          'long_description': '178'
        },
        {
          'system_id': 265,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Niece/Great Aunt (Maternal)',
          'long_description': '229'
        },
        {
          'system_id': 266,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Niece/Great Aunt (Paternal)',
          'long_description': '230'
        },
        {
          'system_id': 267,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Niece/Great Uncle (Maternal)',
          'long_description': '235'
        },
        {
          'system_id': 268,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Niece/Great Uncle (Paternal)',
          'long_description': '236'
        },
        {
          'system_id': 269,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Niece/Uncle (Maternal)',
          'long_description': '298'
        },
        {
          'system_id': 270,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'NC',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Niece/Uncle (Paternal)',
          'long_description': '299'
        },
        {
          'system_id': 271,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FR',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'No Relation/No Relation',
          'long_description': '271'
        },
        {
          'system_id': 272,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'CP',
          'third_id': '0000000000',
          'other_code': 'UF',
          'inactive_indicator': true,
          'short_description': 'Non-Custodial Parent/Daughter',
          'long_description': '200'
        },
        {
          'system_id': 273,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'CP',
          'third_id': '0000000000',
          'other_code': 'UM',
          'inactive_indicator': true,
          'short_description': 'Non-Custodial Parent/Son',
          'long_description': '294'
        },
        {
          'system_id': 274,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Other Relative/Other Relative',
          'long_description': '274'
        },
        {
          'system_id': 275,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Significant Other/Significant Other',
          'long_description': '275'
        },
        {
          'system_id': 276,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SI',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Sister/Brother',
          'long_description': '182'
        },
        {
          'system_id': 277,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SI',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Sister/Brother (Half)',
          'long_description': '183'
        },
        {
          'system_id': 278,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SI',
          'third_id': '0000000000',
          'other_code': 'FM',
          'inactive_indicator': false,
          'short_description': 'Sister/Brother (Step)',
          'long_description': '184'
        },
        {
          'system_id': 279,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SI',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Sister/Sister',
          'long_description': '279'
        },
        {
          'system_id': 280,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SI',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Sister/Sister (Half)',
          'long_description': '280'
        },
        {
          'system_id': 281,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SI',
          'third_id': '0000000000',
          'other_code': 'FF',
          'inactive_indicator': false,
          'short_description': 'Sister/Sister (Step)',
          'long_description': '281'
        },
        {
          'system_id': 282,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'MU',
          'inactive_indicator': false,
          'short_description': 'Son/De Facto Parent',
          'long_description': '202'
        },
        {
          'system_id': 283,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mM',
          'inactive_indicator': false,
          'short_description': 'Son/Father (Adoptive)',
          'long_description': '209'
        },
        {
          'system_id': 284,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mM',
          'inactive_indicator': false,
          'short_description': 'Son/Father (Alleged)',
          'long_description': '210'
        },
        {
          'system_id': 285,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mM',
          'inactive_indicator': false,
          'short_description': 'Son/Father (Birth)',
          'long_description': '211'
        },
        {
          'system_id': 286,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FS',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Son/Father (Foster)',
          'long_description': '212'
        },
        {
          'system_id': 287,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mM',
          'inactive_indicator': false,
          'short_description': 'Son/Father (Presumed)',
          'long_description': '213'
        },
        {
          'system_id': 288,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SS',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Son/Father (Step)',
          'long_description': '214'
        },
        {
          'system_id': 289,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mF',
          'inactive_indicator': false,
          'short_description': 'Son/Mother (Adoptive)',
          'long_description': '250'
        },
        {
          'system_id': 290,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mF',
          'inactive_indicator': false,
          'short_description': 'Son/Mother (Alleged)',
          'long_description': '251'
        },
        {
          'system_id': 291,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mF',
          'inactive_indicator': false,
          'short_description': 'Son/Mother (Birth)',
          'long_description': '252'
        },
        {
          'system_id': 292,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'FS',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Son/Mother (Foster)',
          'long_description': '253'
        },
        {
          'system_id': 293,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SS',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Son/Mother (Step)',
          'long_description': '254'
        },
        {
          'system_id': 294,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'MU',
          'inactive_indicator': true,
          'short_description': 'Son/Non-Custodial Parent',
          'long_description': '273'
        },
        {
          'system_id': 295,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'SPL',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Spouse/Spouse',
          'long_description': '295'
        },
        {
          'system_id': 296,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'UN',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Uncle/Nephew (Maternal)',
          'long_description': '261'
        },
        {
          'system_id': 297,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'UN',
          'third_id': '0000000000',
          'other_code': 'MM',
          'inactive_indicator': false,
          'short_description': 'Uncle/Nephew (Paternal)',
          'long_description': '262'
        },
        {
          'system_id': 298,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'UN',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Uncle/Niece (Maternal)',
          'long_description': '269'
        },
        {
          'system_id': 299,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'UN',
          'third_id': '0000000000',
          'other_code': 'MF',
          'inactive_indicator': false,
          'short_description': 'Uncle/Niece (Paternal)',
          'long_description': '270'
        },
        {
          'system_id': 300,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'UNK',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Unknown/Unknown',
          'long_description': '300'
        },
        {
          'system_id': 301,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Ward/Guardian',
          'long_description': '241'
        },
        {
          'system_id': 5620,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Ff',
          'inactive_indicator': false,
          'short_description': 'Mother/Daughter (Presumed)',
          'long_description': '198'
        },
        {
          'system_id': 5993,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Child/Residential Facility Staff',
          'long_description': '5994'
        },
        {
          'system_id': 5994,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'OTH',
          'third_id': '0000000000',
          'other_code': 'UU',
          'inactive_indicator': false,
          'short_description': 'Residential Facility Staff/Child',
          'long_description': '5993'
        },
        {
          'system_id': 6360,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'S',
          'third_id': '0000000000',
          'other_code': 'mF',
          'inactive_indicator': false,
          'short_description': 'Son/Mother (Presumed)',
          'long_description': '6361'
        },
        {
          'system_id': 6361,
          'meta_code': 'CLNTRELC',
          'category_id': 0,
          'logical_id': 'M',
          'third_id': '0000000000',
          'other_code': 'Fm',
          'inactive_indicator': false,
          'short_description': 'Mother/Son (Presumed)',
          'long_description': '6360'
        }
      ]
    end
  end
end
# rubocop:enable Metrics/ClassLength, Metrics/MethodLength
