var clientMock = [
  // 1
  {
    common_first_name: 'GI Joe',
    common_middle_name: 'George',
    common_last_name: 'Harris',
    suffix_title_description: 'Hey!',
    social_security_number: '349-23-8712',
    birth_dt: '13/09/91',
    adopted_age: '6',
    identifier: '27683',
    alien_registration_number: 'abc1',
    driver_licens_number: 'abc2',
    gender_code: 'abc3',
    material_status_type: 'abc4',
    ageUnit: 'abc5',
    name_type: 'abc6',
    driver_license_state_code_type: 'abc6',
    primary_language_type: 'abc7',
    secondary_language_type: 'abc8',
    litrate_code: 'abc9',
    incapacitated_parent_code: 'abc11',
    address: {
      id: '0Ki',
      description: 'Hello',
      city: 'Sacramento',
      emergency_phone: '916-292-8831',
      emergency_phone_extension: '331',
      foreign_address_exists: true,
      government_entity_code: '1',
      message_phone: '916-292-8831',
      message_phone_extension: '331',
      other_header_address: 'Folsom Blvd',
      post_direction_text_code: '112',
      pre_direction_text_code: '123',
      primary_phone: '916-292-8831',
      primary_phone_extension: '123',
      state: 'Califoria',
      state_code: 10,
      street_name: 'Folsom Blvd',
      street_number: '10833',
      street_suffix_code: 90,
      unit_designator_code: '78324',
      unit_number: '123',
      zip: '96790',
      zip_suffix: 847,
      longitude: -121.46,
      lattitude: 38.66,
    },
  },

  // 2
  {
    common_first_name: 'Harry',
    common_middle_name: 'Jr',
    common_last_name: 'Sohal',
    suffix_title_description: 'Yo!',
    social_security_number: '387-123-4567',
    birth_dt: '13/09/71',
    adopted_age: '4',
    identifier: '3829',
    alien_registration_number: 'def1',
    driver_licens_number: 'def2',
    gender_code: 'def3',
    material_status_type: 'def4',
    ageUnit: 'def5',
    name_type: 'def6',
    driver_license_state_code_type: 'def6',
    primary_language_type: 'def7',
    secondary_language_type: 'def8',
    litrate_code: 'def9',
    incapacitated_parent_code: 'def11',
    address: {
      id: '12Ki',
      description: 'Duh!',
      city: 'Rocklin',
      emergency_phone: '913-234-5678',
      emergency_phone_extension: '123',
      foreign_address_exists: true,
      government_entity_code: '2',
      message_phone: '913-234-5678',
      message_phone_extension: '123',
      other_header_address: 'abcd',
      post_direction_text_code: '123442',
      pre_direction_text_code: '873',
      primary_phone: '913-234-5678',
      primary_phone_extension: '123',
      state: 'California',
      state_code: 12,
      street_name: 'Sunrise Blvd',
      street_number: '133',
      street_suffix_code: 40,
      unit_designator_code: '324',
      unit_number: '998',
      zip: '66790',
      zip_suffix: 557,
      longitude: -121.46,
      lattitude: 37.66,
    },
  },
  // 3

  {
    common_first_name: 'Ronney',
    common_middle_name: 'Sr',
    common_last_name: 'Gibbs',
    suffix_title_description: 'HUH!',
    social_security_number: '381-16-7868',
    birth_dt: '1/10/81',
    adopted_age: '9',
    identifier: '39',
    alien_registration_number: 'ghi1',
    driver_licens_number: 'ghi2',
    gender_code: 'ghi3',
    material_status_type: 'ghi4',
    ageUnit: 'ghi5',
    name_type: 'ghi6',
    driver_license_state_code_type: 'ghi6',
    primary_language_type: 'ghi7',
    secondary_language_type: 'ghi8',
    litrate_code: 'ghi9',
    incapacitated_parent_code: 'ghi11',
    address: {
      id: 'fdKi',
      description: 'Lol!',
      city: 'Natomas',
      emergency_phone: '871-564-9865',
      emergency_phone_extension: '765',
      foreign_address_exists: false,
      government_entity_code: '9',
      message_phone: '871-564-9865',
      message_phone_extension: '765',
      other_header_address: '672',
      post_direction_text_code: '234',
      pre_direction_text_code: '546',
      primary_phone: '871-564-9865',
      primary_phone_extension: '765',
      state: 'California',
      state_code: 10,
      street_name: 'Natomas Blvd',
      street_number: '53',
      street_suffix_code: 30,
      unit_designator_code: '14',
      unit_number: '234',
      zip: '86790',
      zip_suffix: 3423,
      longitude: -121.16,
      lattitude: 37.56,
    },
  },
  // 4
  {
    common_first_name: 'Jame',
    common_middle_name: '',
    common_last_name: 'Harrison',
    suffix_title_description: 'Dummy',
    social_security_number: '321-34-6712',
    birth_dt: '1/10/01',
    adopted_age: '8',
    identifier: '49',
    alien_registration_number: '434',
    driver_licens_number: 'jkl2',
    gender_code: 'jkl3',
    material_status_type: 'jkl4',
    ageUnit: 'jkl5',
    name_type: 'jkl6',
    driver_license_state_code_type: 'jkl6',
    primary_language_type: 'jkl7',
    secondary_language_type: 'jkl8',
    litrate_code: 'jkl9',
    incapacitated_parent_code: 'jkl11',
    address: {
      id: '213i',
      description: 'Woah!',
      city: 'Roseville',
      emergency_phone: '765-453-7889',
      emergency_phone_extension: '245',
      foreign_address_exists: false,
      government_entity_code: '99',
      message_phone: '765-453-7889',
      message_phone_extension: '245',
      other_header_address: 'rr',
      post_direction_text_code: '2324',
      pre_direction_text_code: '434',
      primary_phone: '765-453-7889',
      primary_phone_extension: '245',
      state: 'California',
      state_code: 10,
      street_name: 'Roseville Blvd',
      street_number: '223',
      street_suffix_code: 40,
      unit_designator_code: '56',
      unit_number: '565',
      zip: '46790',
      zip_suffix: 3465,
      longitude: -121.76,
      lattitude: 37.36,
    },
  },

  // 5

  {
    common_first_name: 'Greg',
    common_middle_name: 'Sr',
    common_last_name: 'Yen',
    suffix_title_description: 'Mock',
    social_security_number: '24325',
    birth_dt: '11/11/11',
    adopted_age: '3',
    identifier: '534',
    alien_registration_number: 'ted1',
    driver_licens_number: 'ted2',
    gender_code: 'ted3',
    material_status_type: 'ted4',
    ageUnit: 'ted5',
    name_type: 'ted6',
    driver_license_state_code_type: 'ted6',
    primary_language_type: 'ted7',
    secondary_language_type: 'ted8',
    litrate_code: 'ted9',
    incapacitated_parent_code: 'ted11',
    address: {
      id: 'rg',
      description: 'HeH!',
      city: 'Elk Grove',
      emergency_phone: '345-342-4646',
      emergency_phone_extension: '357',
      foreign_address_exists: false,
      government_entity_code: '66',
      message_phone: '345-342-4646',
      message_phone_extension: '357',
      other_header_address: '1345',
      post_direction_text_code: '9876',
      pre_direction_text_code: '456',
      primary_phone: '345-342-4646',
      primary_phone_extension: '357',
      state: 'California',
      state_code: 10,
      street_name: 'Elk Blvd',
      street_number: '93',
      street_suffix_code: 30,
      unit_designator_code: '44',
      unit_number: '4567',
      zip: '56790',
      zip_suffix: 53,
      longitude: -121.46,
      lattitude: 37.86,
    },
  },
];

export default clientMock;
