// action types
export const FETCH_SAFETY_ALERTS_API_CALL_REQUEST =
  'FETCH_SAFETY_ALERTS_API_CALL_REQUEST';
export const FETCH_SAFETY_ALERTS_API_CALL_SUCCESS =
  'FETCH_SAFETY_ALERTS_API_CALL_SUCCESS';
export const FETCH_SAFETY_ALERTS_API_CALL_FAILURE =
  'FETCH_SAFETY_ALERTS_API_CALL_FAILURE';

export const FETCH_RELATED_CLIENTS_API_CALL_REQUEST =
  'FETCH_RELATED_CLIENTS_API_CALL_REQUEST';
export const FETCH_RELATED_CLIENTS_API_CALL_SUCCESS =
  'FETCH_RELATED_CLIENTS_API_CALL_SUCCESS';
export const FETCH_RELATED_CLIENTS_API_CALL_FAILURE =
  'FETCH_RELATED_CLIENTS_API_CALL_FAILURE';
