export default [
  {
    system_id: 1516,
    meta_code: 'RFR_RSPC',
    category_id: 0,
    logical_id: '0001',
    third_id: '0000000000',
    other_code: '',
    inactive_indicator: false,
    short_description: '3 Day',
    long_description: '',
  },
  {
    system_id: 1517,
    meta_code: 'RFR_RSPC',
    category_id: 0,
    logical_id: '0002',
    third_id: '0000000000',
    other_code: '',
    inactive_indicator: false,
    short_description: '5 Day',
    long_description: '',
  },
  {
    system_id: 1518,
    meta_code: 'RFR_RSPC',
    category_id: 0,
    logical_id: '0003',
    third_id: '0000000000',
    other_code: '',
    inactive_indicator: false,
    short_description: '10 Day',
    long_description: '',
  },
  {
    system_id: 1519,
    meta_code: 'RFR_RSPC',
    category_id: 0,
    logical_id: '0004',
    third_id: '0000000000',
    other_code: '',
    inactive_indicator: false,
    short_description: 'Evaluate Out',
    long_description: '',
  },
  {
    system_id: 1520,
    meta_code: 'RFR_RSPC',
    category_id: 0,
    logical_id: '0005',
    third_id: '0000000000',
    other_code: '',
    inactive_indicator: false,
    short_description: 'Immediate',
    long_description: '',
  },
  {
    system_id: 1521,
    meta_code: 'RFR_RSPC',
    category_id: 0,
    logical_id: '0006',
    third_id: '0000000000',
    other_code: '',
    inactive_indicator: false,
    short_description: 'N/A Secondary Report',
    long_description: '',
  },
];
