export = AddressService;
declare class AddressService {
  static fetch(): Promise<AddressService.Address[]>;
}
declare namespace AddressService {
  export interface Address {
    /**
     * ADDRESS.ID - A system generated number used to uniquely identify each ADDRESS. This ID is composed of a base 62 Creation Timestamp and the STAFF_PERSON ID (a sequential 3 digit base 62 number generated by the system). This value eliminates the need for an additional set of Creation Timestamp and Creation User ID which is needed to satisfy the Audit Trail requirement. ,
     */
    id?: string;
    /**
     * DESCRIPTION - Any additional information pertaining to the ADDRESS which may include directions for getting to the ADDRESS, description of the residence, or foreign phone number, as well as the name and hours (e.g., 3pm to 6pm) of the day care for the child CLIENT who is at the day care center. If the correspondent ADDRESS TYPE value for this ADDRESS is 'Homeless', the location of where the CLIENT lives must be enter here (e.g., shelter care). ,
     */
    description?: string;
    /**
     * ADDRESS.CITY_NAME - The name of the city for the ADDRESS. ,
     */
    city?: string;
    /**
     * ADDRESS.EMERGENCY_PHONE - An alternate or emergency phone number for the CLIENT. ,
     */
    emergency_phone?: string;
    /**
     * ADDRESS.FOREIGN_ADDRESS_IND_VAR - This indicator variable is used to indicate if there are any occurrences of FOREIGN_ADDRESSs related to this ADDRESS. This will save unnecessary processing time from searching for information that does not exist in the database.
     */
    foreign_address_exists?: boolean;
    /**
     * ADDRESS.GOVERNMENT_ENTITY_TYPE - The system generated number which represents the specific county (e.g., Napa, Sacramento, Fresno, etc.) within the state of California for a specific CLIENT's ADDRESS. Additional info can be reached via dictionaries resource by 'GVR_ENTC' key. ,
     */
    government_entity_code?: integer;
    /**
     * ADDRESS.MESSAGE_PHONE_NUMBER - An alternate or message phone number for the CLIENT.
     */
    message_phone?: string;
    /**
     * ADDRESS.MESSAGE_PHONE_EXTENSION_NUMBER - The message phone extension number of the CLIENT. ,
     */
    message_phone_extension?: string;
    /**
     * ADDRESS.OTHER_HEADER_ADDRESS - Any additional address information which will be placed above the standard postal Delivery Address Line. This may include the name of the In Care Of person, firm, institution or building to which the piece of mail is directed. ,
     */
    other_header_address?: string;
    /**
     * ADDRESS.POST_DIRECTION_TEXT_CODE - The two-letter postal abbreviation following the Street Name and Street Suffix which gives directional information about a specific CLIENT's ADDRESS for delivery purposes. For example NE (Northeast), SW (Southwest), etc.,
     */
    post_direction_text_code?: string;
    /**
     * ADDRESS.PRE_DIRECTION_TEXT_CODE - The two-letter postal abbreviation preceding the Street Name and Street Suffix which gives directional information about a specific CLIENT's ADDRESS for delivery purposes. For example NE (Northeast), SW (Southwest), etc. ,
     */
    pre_direction_text_code?: string;
    /**
     * ADDRESS.PRIMARY_PHONE_NUMBER - The primary phone number including area code of the CLIENT.
     */
    /**
     * ADDRESS.PRIMARY_PHONE_NUMBER - The primary phone number including area code of the CLIENT.
     */
    primary_phone?: string;
    /**
     * ADDRESS.PRIMARY_PHONE_EXTENSION_NUMBER - The primary phone extension number of the CLIENT.
     */
    primary_phone_extension?: string;
    /**
     * ADDRESS.STATE_CODE_TYPE - The system generated number which identifies the State for a specific CLIENT's ADDRESS (e.g. California, Hawaii, Texas, etc). Additional info can be reached via dictionaries resource by 'STATE_C' key.
     */
    state_code?: integer;
    /**
     * ADDRESS.Street Name
     */
    street_name?: string;
    /**
     * ADDRESS.STREET_NUMBER - The street or house number associated with the street name as part of the ADDRESS. This may include the fractional or alphabetic modifier (e.g. A-17, 119-10, 39.2, 100 1/2, etc).
     */
    street_number?: string;
    /**
     * ADDRESS.STREET_SUFFIX_TYPE - The system generated number assigned to each postal standard abbreviation following the Street Name which further identifies the uniqueness of the ADDRESS. E.g. Road, Plaza, Square, etc. Additional info can be reached via dictionaries resource by 'ST_SFX_C' key. ,
     */

    street_suffix_code?: integer;
    /**
     * ADDRESS.UNIT_DESIGNATOR_TYPE - The system generated number assigned for each standard postal abbreviation which further defines the location of a specific CLIENT's ADDRESS (e.g. APT (Apartment), BLDG (Building), FL (floor), etc).Additional info can be reached via dictionaries resource by 'UNT_DSGC' key. ,
     */
    unit_designator_code?: integer;
    /**
     * ADDRESS.UNIT_NUMBER - The actual alphanumeric ID following the standard postal abbreviation (UNIT DESIGNATOR) which further defines the position of ADDRESS (e.g. 200A, 2C, etc). ,
     */
    unit_number?: string;
    /**
     * ADDRESS.ZIP_NUMBER - The first five digits of the zip code for ADDRESS.
     */
    zip?: string;
    /**
     * ADDRESS.ZIP_SUFFIX_NUMBER - The last four digits of the zip code for an ADDRESS.
     */
    zip_suffix?: string;
  }
}
